// <auto-generated>
// Transpiled from Overt module `hello`.
// DO NOT EDIT THIS FILE. Edits are overwritten on every build.
// Debug symbols (portable PDB) map runtime errors and breakpoints
// back to the original .ov source via the #line directives below;
// stack traces, debuggers, and source-link tooling all resolve to
// the Overt file, not this generated C#.
// </auto-generated>
#nullable enable

using System;
using System.Threading.Tasks;
using Overt.Runtime;
using static Overt.Runtime.Prelude;

namespace Overt.Generated.Hello;


public static class Module
{
    // !{io}
    public static Result<Unit, IoError> main()
    {
        var __q_0 = (println("Hello, LLM!"));
        if (!__q_0.IsOk) return Err<IoError>(__q_0.UnwrapErr());
        var __qv_0 = __q_0.Unwrap();
        return Ok<Unit>((Unit)Unit.Value);
    }

}
