// <auto-generated>
// Transpiled from Overt module `hello`.
// </auto-generated>
#nullable enable

using System;
using System.Threading.Tasks;
using Overt.Runtime;
using static Overt.Runtime.Prelude;

namespace Overt.Generated.Hello;


public static class Module
{
    // !{io}
    public static Result<Unit, IoError> Main()
    {
        (println("Hello, LLM!")).Unwrap();
        return Ok(Unit.Value);
    }

}
