using System.Text;
using Overt.Compiler.Syntax;

namespace Overt.Backend.Go;

/// <summary>
/// Hello-world-grade Go back end. Lowers a small subset of the Overt AST
/// to Go source so that a transpiled module can be built with `go build`
/// and run as a native binary. The C# back end (<c>CSharpEmitter</c>) is
/// the reference; this emitter is intentionally several feature levels
/// behind it.
///
/// Currently supported:
///   - module declaration → `package main` (assumes the module is the entry)
///   - <c>fn name(params) !{io} -> Result&lt;(), IoError&gt;</c> with a
///     literal-string println body
///   - <c>println("...")</c> with optional <c>?</c> propagation
///   - <c>Ok(())</c> as the trailing expression
///
/// Out of scope here, queued for follow-ups: enums, records, generics,
/// match, traits, struct types, the rest of the prelude, full effect-row
/// propagation. The first goal is to prove the cross-back-end IR contract
/// holds water; feature parity with the C# emitter is incremental work.
/// </summary>
public static class GoEmitter
{
    /// <summary>Emit Go source for a single Overt module. Returns the
    /// full file content; the caller writes it to disk and arranges for
    /// `go build` / `go run` against the runtime under `runtime/go`.</summary>
    public static string Emit(ModuleDecl module)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// Code generated by Overt.Backend.Go. DO NOT EDIT.");
        sb.AppendLine($"// Transpiled from Overt module `{module.Name}`.");
        sb.AppendLine();
        sb.AppendLine("package main");
        sb.AppendLine();
        sb.AppendLine("import (");
        sb.AppendLine("\t\"os\"");
        sb.AppendLine("\t\"overt-runtime/overt\"");
        sb.AppendLine(")");
        sb.AppendLine();

        var hasUserMain = false;
        foreach (var decl in module.Declarations)
        {
            if (decl is FunctionDecl fn)
            {
                EmitFunction(sb, fn);
                if (fn.Name == "main") hasUserMain = true;
                sb.AppendLine();
            }
            else
            {
                throw new NotSupportedException(
                    $"Go back end does not yet handle {decl.GetType().Name}; "
                    + "currently only FunctionDecl is supported.");
            }
        }

        if (hasUserMain)
        {
            // Synthesize the Go-side `func main()` that drives the
            // user's `main` (renamed to `__overt_main` to avoid the
            // collision with Go's reserved entry-point name) and
            // propagates a non-zero exit on Err.
            sb.AppendLine("func main() {");
            sb.AppendLine("\tr := __overt_main()");
            sb.AppendLine("\tif !r.IsOk {");
            sb.AppendLine("\t\t_ = overt.Eprintln(r.Err.Error())");
            sb.AppendLine("\t\tos.Exit(1)");
            sb.AppendLine("\t}");
            sb.AppendLine("}");
        }

        // Suppress "imported and not used" diagnostics from `go build`
        // when a module has no user main and never references `os`. The
        // runtime is always referenced (Result types) so it doesn't
        // need this dance.
        if (!hasUserMain)
        {
            sb.AppendLine("var _ = os.Exit");
        }

        return sb.ToString();
    }

    private static void EmitFunction(StringBuilder sb, FunctionDecl fn)
    {
        // Rename the user's `main` so the synthesized `func main()` can
        // coexist with it; everything else keeps its source name.
        var goName = fn.Name == "main" ? "__overt_main" : fn.Name;

        // Parameters: only zero-arg fns supported for now.
        if (fn.Parameters.Length != 0)
        {
            throw new NotSupportedException(
                "Go back end does not yet handle parameters; "
                + $"`fn {fn.Name}` declares {fn.Parameters.Length}.");
        }

        sb.Append($"func {goName}() ");
        EmitReturnType(sb, fn.ReturnType);
        sb.AppendLine(" {");
        EmitBlock(sb, fn.Body, indent: 1);
        sb.AppendLine("}");
    }

    private static void EmitReturnType(StringBuilder sb, TypeExpr? type)
    {
        // The only currently-recognized return type is
        // `Result<(), IoError>`, which lowers to
        // `overt.Result[overt.Unit, overt.IoError]`. Everything else
        // is a wide-open follow-up.
        if (type is NamedType { Name: "Result" } nt && nt.TypeArguments.Length == 2
            && nt.TypeArguments[0] is UnitType
            && nt.TypeArguments[1] is NamedType { Name: "IoError" })
        {
            sb.Append("overt.Result[overt.Unit, overt.IoError]");
            return;
        }
        if (type is null || type is UnitType)
        {
            // `-> ()` becomes a Go fn with no return; emit the empty
            // return-type slot.
            return;
        }
        throw new NotSupportedException(
            "Go back end currently only emits return type "
            + "`Result<(), IoError>` or `()`; got: " + (type?.ToString() ?? "<null>"));
    }

    private static void EmitBlock(StringBuilder sb, BlockExpr block, int indent)
    {
        var pad = new string('\t', indent);
        var qCounter = 0;
        foreach (var stmt in block.Statements)
        {
            sb.Append(pad);
            EmitStatement(sb, stmt, indent, ref qCounter);
            sb.AppendLine();
        }
        if (block.TrailingExpression is not null)
        {
            sb.Append(pad);
            sb.Append("return ");
            EmitExpression(sb, block.TrailingExpression);
            sb.AppendLine();
        }
    }

    private static void EmitStatement(StringBuilder sb, Statement stmt, int indent, ref int qCounter)
    {
        switch (stmt)
        {
            case ExpressionStmt es:
                if (es.Expression is PropagateExpr pe)
                {
                    EmitPropagate(sb, pe, indent, ref qCounter);
                }
                else
                {
                    EmitExpression(sb, es.Expression);
                }
                break;

            case DiscardStmt ds:
                sb.Append("_ = ");
                EmitExpression(sb, ds.Value);
                break;

            default:
                throw new NotSupportedException(
                    $"Go back end does not yet handle {stmt.GetType().Name}.");
        }
    }

    private static void EmitPropagate(StringBuilder sb, PropagateExpr pe, int indent, ref int qCounter)
    {
        // Lower `expr?` to:
        //   __q_N := <expr>
        //   if !__q_N.IsOk {
        //       return overt.Err[overt.Unit, overt.IoError](__q_N.Err)
        //   }
        // The hello-world function only ever has Result<Unit, IoError>
        // as its return type, so the type parameters on Err are fixed
        // for now. A full implementation would consult the type checker.
        var pad = new string('\t', indent);
        var name = $"__q_{qCounter++}";
        sb.Append($"{name} := ");
        EmitExpression(sb, pe.Operand);
        sb.AppendLine();
        sb.Append(pad);
        sb.AppendLine($"if !{name}.IsOk {{");
        sb.Append(pad);
        sb.AppendLine($"\treturn overt.Err[overt.Unit, overt.IoError]({name}.Err)");
        sb.Append(pad);
        sb.Append("}");
    }

    private static void EmitExpression(StringBuilder sb, Expression expr)
    {
        switch (expr)
        {
            case StringLiteralExpr sl:
                // sl.Value is the raw lexeme including surrounding quotes
                // and the original source's escape sequences. Overt's
                // string escape syntax is C-compatible (\n, \t, \\, \"),
                // so the lexeme transfers to Go verbatim for the scaffold-
                // grade subset we currently support. A future feature
                // expansion that allows `\u` sequences will need a real
                // decode/re-encode pass; cf. the C# emitter at
                // CSharpEmitter.cs around line 2205.
                sb.Append(sl.Value);
                break;

            case UnitExpr:
                sb.Append("overt.UnitValue");
                break;

            case CallExpr call:
                EmitCall(sb, call);
                break;

            case IdentifierExpr id:
                // Heuristic: lowercase-leading names are local fns or
                // prelude exports (println / eprintln); uppercase-leading
                // are constructors (Ok / Err) routed through the runtime.
                sb.Append(MapIdentifier(id.Name));
                break;

            default:
                throw new NotSupportedException(
                    $"Go back end does not yet handle expression {expr.GetType().Name}.");
        }
    }

    private static void EmitCall(StringBuilder sb, CallExpr call)
    {
        // Special-case the constructors: `Ok(x)` and `Err(e)` need
        // explicit type parameters in Go, since there's no contextual
        // type inference at the call site.
        if (call.Callee is IdentifierExpr { Name: "Ok" } && call.Arguments.Length == 1)
        {
            sb.Append("overt.Ok[overt.Unit, overt.IoError](");
            EmitExpression(sb, call.Arguments[0].Value);
            sb.Append(')');
            return;
        }
        if (call.Callee is IdentifierExpr { Name: "Err" } && call.Arguments.Length == 1)
        {
            sb.Append("overt.Err[overt.Unit, overt.IoError](");
            EmitExpression(sb, call.Arguments[0].Value);
            sb.Append(')');
            return;
        }

        EmitExpression(sb, call.Callee);
        sb.Append('(');
        for (var i = 0; i < call.Arguments.Length; i++)
        {
            if (i > 0) sb.Append(", ");
            EmitExpression(sb, call.Arguments[i].Value);
        }
        sb.Append(')');
    }

    private static string MapIdentifier(string name) => name switch
    {
        "println" => "overt.Println",
        "eprintln" => "overt.Eprintln",
        _ => name,
    };

}
