using System.Text;
using Overt.Compiler.Syntax;

namespace Overt.Backend.Go;

/// <summary>
/// Hello-world-grade Go back end. Lowers a small subset of the Overt AST
/// to Go source so that a transpiled module can be built with `go build`
/// and run as a native binary. The C# back end (<c>CSharpEmitter</c>) is
/// the reference; this emitter is intentionally several feature levels
/// behind it.
///
/// Currently supported:
///   - module declaration → `package main` (assumes the module is the entry)
///   - <c>fn name(params) !{io} -> Result&lt;(), IoError&gt;</c> with a
///     literal-string println body
///   - <c>println("...")</c> with optional <c>?</c> propagation
///   - <c>Ok(())</c> as the trailing expression
///
/// Out of scope here, queued for follow-ups: enums, records, generics,
/// match, traits, struct types, the rest of the prelude, full effect-row
/// propagation. The first goal is to prove the cross-back-end IR contract
/// holds water; feature parity with the C# emitter is incremental work.
/// </summary>
public static class GoEmitter
{
    /// <summary>Emit Go source for a single Overt module. Returns the
    /// full file content; the caller writes it to disk and arranges for
    /// `go build` / `go run` against the runtime under `runtime/go`.</summary>
    public static string Emit(ModuleDecl module)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// Code generated by Overt.Backend.Go. DO NOT EDIT.");
        sb.AppendLine($"// Transpiled from Overt module `{module.Name}`.");
        sb.AppendLine();
        sb.AppendLine("package main");
        sb.AppendLine();
        sb.AppendLine("import (");
        sb.AppendLine("\t\"os\"");
        sb.AppendLine("\t\"overt-runtime/overt\"");
        sb.AppendLine(")");
        sb.AppendLine();

        var hasUserMain = false;
        foreach (var decl in module.Declarations)
        {
            switch (decl)
            {
                case FunctionDecl fn:
                    EmitFunction(sb, fn);
                    if (fn.Name == "main") hasUserMain = true;
                    sb.AppendLine();
                    break;

                case RecordDecl rec:
                    EmitRecord(sb, rec);
                    sb.AppendLine();
                    break;

                default:
                    throw new NotSupportedException(
                        $"Go back end does not yet handle {decl.GetType().Name}.");
            }
        }

        if (hasUserMain)
        {
            // Synthesize the Go-side `func main()` that drives the
            // user's `main` (renamed to `__overt_main` to avoid the
            // collision with Go's reserved entry-point name) and
            // propagates a non-zero exit on Err.
            sb.AppendLine("func main() {");
            sb.AppendLine("\tr := __overt_main()");
            sb.AppendLine("\tif !r.IsOk {");
            sb.AppendLine("\t\t_ = overt.Eprintln(r.Err.Error())");
            sb.AppendLine("\t\tos.Exit(1)");
            sb.AppendLine("\t}");
            sb.AppendLine("}");
        }

        // Suppress "imported and not used" diagnostics from `go build`
        // when a module has no user main and never references `os`. The
        // runtime is always referenced (Result types) so it doesn't
        // need this dance.
        if (!hasUserMain)
        {
            sb.AppendLine("var _ = os.Exit");
        }

        return sb.ToString();
    }

    private static void EmitFunction(StringBuilder sb, FunctionDecl fn)
    {
        // Rename the user's `main` so the synthesized `func main()` can
        // coexist with it; everything else keeps its source name.
        var goName = fn.Name == "main" ? "__overt_main" : fn.Name;

        sb.Append($"func {goName}(");
        for (var i = 0; i < fn.Parameters.Length; i++)
        {
            if (i > 0) sb.Append(", ");
            var p = fn.Parameters[i];
            sb.Append(p.Name);
            sb.Append(' ');
            sb.Append(LowerType(p.Type));
        }
        sb.Append(") ");
        EmitReturnType(sb, fn.ReturnType);
        sb.AppendLine(" {");
        // Functions whose return type lowers to no Go return slot
        // (`-> ()` or null) don't want `return <expr>` for a trailing Unit;
        // every other shape does want a trailing return.
        var asReturn = fn.ReturnType is not null && fn.ReturnType is not UnitType;
        EmitBlock(sb, fn.Body, indent: 1, asReturn);
        sb.AppendLine("}");
    }

    /// <summary>
    /// Lower an Overt <see cref="TypeExpr"/> to a Go type string. Covers the
    /// primitive subset, the stdlib generics (Result / Option), and any
    /// user-declared NamedType that's already a known struct in the same
    /// emitted package (records). Unrecognized cases throw so silent
    /// miscompilation isn't possible.
    /// </summary>
    private static string LowerType(TypeExpr? type) => type switch
    {
        NamedType { Name: "Int" } => "int",
        NamedType { Name: "Int64" } => "int64",
        NamedType { Name: "Bool" } => "bool",
        NamedType { Name: "String" } => "string",
        NamedType { Name: "Float" } => "float64",
        UnitType => "overt.Unit",
        NamedType { Name: "Result" } nt when nt.TypeArguments.Length == 2
            => $"overt.Result[{LowerType(nt.TypeArguments[0])}, {LowerType(nt.TypeArguments[1])}]",
        NamedType { Name: "Option" } nt when nt.TypeArguments.Length == 1
            => $"overt.Option[{LowerType(nt.TypeArguments[0])}]",
        NamedType { Name: "IoError" } => "overt.IoError",
        // User-declared record types: the parser produces NamedType with
        // the record's source name and zero type arguments. Refer to it
        // by the same name in Go (we emit records into `package main`).
        NamedType nt when nt.TypeArguments.Length == 0 => nt.Name,
        null => "overt.Unit",
        _ => throw new NotSupportedException(
            "Go back end does not yet handle type expression " + type.GetType().Name
            + (type is NamedType nm ? $" (Name = {nm.Name})" : "")),
    };

    /// <summary>
    /// Lower an Overt <see cref="RecordDecl"/> to a Go struct type. Records
    /// are immutable in Overt; Go has no first-class immutable struct, but
    /// the emitter never emits mutation against fields, so the consumer
    /// observes the same semantics. Field names are kept lowercase, which
    /// makes them unexported in Go terms — fine for our single-package
    /// `package main` layout. Cross-package use will need a capitalization
    /// pass when we get there.
    /// </summary>
    private static void EmitRecord(StringBuilder sb, RecordDecl rec)
    {
        sb.AppendLine($"type {rec.Name} struct {{");
        foreach (var field in rec.Fields)
        {
            sb.Append('\t');
            sb.Append(field.Name);
            sb.Append(' ');
            sb.AppendLine(LowerType(field.Type));
        }
        sb.AppendLine("}");
    }

    private static void EmitReturnType(StringBuilder sb, TypeExpr? type)
    {
        if (type is null || type is UnitType)
        {
            // `-> ()` becomes a Go fn with no return; emit the empty
            // return-type slot.
            return;
        }
        sb.Append(LowerType(type));
    }

    /// <summary>
    /// Emit a block. <paramref name="asReturn"/> controls how the trailing
    /// expression is treated: function bodies with a non-Unit return want
    /// `return <expr>` (true), while if/else branches in statement position
    /// just want `<expr>` as a statement (false). The qCounter is threaded
    /// through so nested ?-propagation gets unique temp-variable names.
    /// </summary>
    private static void EmitBlock(StringBuilder sb, BlockExpr block, int indent, bool asReturn)
    {
        var pad = new string('\t', indent);
        var qCounter = 0;
        foreach (var stmt in block.Statements)
        {
            sb.Append(pad);
            EmitStatement(sb, stmt, indent, ref qCounter);
            sb.AppendLine();
        }
        if (block.TrailingExpression is not null)
        {
            sb.Append(pad);
            // A trailing PropagateExpr is statement-shaped on emit (it lowers
            // to a temp + early-return), so don't prefix with `return`.
            if (block.TrailingExpression is PropagateExpr trailingPe)
            {
                EmitPropagate(sb, trailingPe, indent, ref qCounter);
                sb.AppendLine();
                return;
            }
            // A trailing IfExpr in return position lowers to an if/else
            // statement where each branch recursively returns its own
            // trailing value. This avoids needing an IIFE wrapper for
            // expression-position if/else in the common case (function
            // body whose value is decided by a branch). The recursion
            // bottoms out at non-if trailing expressions, which use the
            // straight `return <expr>` path below.
            if (asReturn && block.TrailingExpression is IfExpr trailingIf)
            {
                EmitIfAsReturn(sb, trailingIf, indent);
                sb.AppendLine();
                return;
            }
            if (asReturn)
            {
                sb.Append("return ");
            }
            EmitExpression(sb, block.TrailingExpression);
            sb.AppendLine();
        }
    }

    /// <summary>
    /// Emit an if/else where each branch returns its own trailing value.
    /// Used when an if-expression appears in return position (the trailing
    /// expression of a function body whose return type isn't Unit).
    /// Recurses on the branches via <see cref="EmitBlock"/> with
    /// <c>asReturn = true</c>, which threads through nested ifs.
    /// </summary>
    private static void EmitIfAsReturn(StringBuilder sb, IfExpr ie, int indent)
    {
        var pad = new string('\t', indent);
        sb.Append("if ");
        EmitExpression(sb, ie.Condition);
        sb.AppendLine(" {");
        EmitBlock(sb, ie.Then, indent + 1, asReturn: true);
        sb.Append(pad);
        if (ie.Else is BlockExpr elseBlock)
        {
            if (elseBlock.Statements.Length == 0
                && elseBlock.TrailingExpression is IfExpr nested)
            {
                sb.Append("} else ");
                EmitIfAsReturn(sb, nested, indent);
            }
            else
            {
                sb.AppendLine("} else {");
                EmitBlock(sb, elseBlock, indent + 1, asReturn: true);
                sb.Append(pad);
                sb.Append('}');
            }
        }
        else
        {
            // No else branch: an if-without-else is type-checked as Unit
            // by the front end (DESIGN.md §4), so it can't appear in
            // return position for a non-Unit fn. Defensive throw.
            throw new NotSupportedException(
                "if-without-else in return position is unreachable per the type checker");
        }
    }

    private static void EmitStatement(StringBuilder sb, Statement stmt, int indent, ref int qCounter)
    {
        switch (stmt)
        {
            case ExpressionStmt es:
                if (es.Expression is PropagateExpr pe)
                {
                    EmitPropagate(sb, pe, indent, ref qCounter);
                }
                else if (es.Expression is IfExpr ie)
                {
                    EmitIfStatement(sb, ie, indent);
                }
                else
                {
                    EmitExpression(sb, es.Expression);
                }
                break;

            case LetStmt ls:
                EmitLet(sb, ls);
                break;

            case DiscardStmt ds:
                sb.Append("_ = ");
                EmitExpression(sb, ds.Value);
                break;

            default:
                throw new NotSupportedException(
                    $"Go back end does not yet handle {stmt.GetType().Name}.");
        }
    }

    /// <summary>
    /// Lower `let x: T = expr` to Go's `var x T = expr`. Overt requires the
    /// type annotation (OV0314), so we always have a T to print. The
    /// target pattern is currently restricted to a bare identifier;
    /// destructuring lets (tuples, records) are a follow-up.
    /// </summary>
    private static void EmitLet(StringBuilder sb, LetStmt ls)
    {
        if (ls.Target is not IdentifierPattern ip)
        {
            throw new NotSupportedException(
                "Go back end does not yet handle destructuring let; "
                + $"got pattern {ls.Target.GetType().Name}.");
        }
        sb.Append("var ");
        sb.Append(ip.Name);
        if (ls.Type is not null)
        {
            sb.Append(' ');
            sb.Append(LowerType(ls.Type));
        }
        sb.Append(" = ");
        EmitExpression(sb, ls.Initializer);
    }

    /// <summary>
    /// Lower a statement-position `if`/`else` to Go's `if`/`else`. Both
    /// branches are blocks; the value of the if-expression is unused at
    /// this position so neither branch needs a trailing-`return`.
    ///
    /// `else if` chains are encoded by the parser as <c>Else =
    /// BlockExpr { TrailingExpression = IfExpr(...) }</c>; we detect that
    /// shape and recurse on the inner IfExpr to produce idiomatic
    /// Go `if/else if/else` instead of nested `else { if ... }`.
    /// Expression-position if/else (let initializer, function arg) is a
    /// follow-up: Go has no ternary, so it needs an immediately-invoked
    /// closure wrapper.
    /// </summary>
    private static void EmitIfStatement(StringBuilder sb, IfExpr ie, int indent)
    {
        var pad = new string('\t', indent);
        sb.Append("if ");
        EmitExpression(sb, ie.Condition);
        sb.AppendLine(" {");
        EmitBlock(sb, ie.Then, indent + 1, asReturn: false);
        sb.Append(pad);
        if (ie.Else is BlockExpr elseBlock)
        {
            // Detect `else if` shape: the else block is a single trailing
            // IfExpr with no other statements.
            if (elseBlock.Statements.Length == 0
                && elseBlock.TrailingExpression is IfExpr nested)
            {
                sb.Append("} else ");
                EmitIfStatement(sb, nested, indent);
            }
            else
            {
                sb.AppendLine("} else {");
                EmitBlock(sb, elseBlock, indent + 1, asReturn: false);
                sb.Append(pad);
                sb.Append('}');
            }
        }
        else
        {
            sb.Append('}');
        }
    }

    private static void EmitPropagate(StringBuilder sb, PropagateExpr pe, int indent, ref int qCounter)
    {
        // Lower `expr?` to:
        //   __q_N := <expr>
        //   if !__q_N.IsOk {
        //       return overt.Err[overt.Unit, overt.IoError](__q_N.Err)
        //   }
        // The hello-world function only ever has Result<Unit, IoError>
        // as its return type, so the type parameters on Err are fixed
        // for now. A full implementation would consult the type checker.
        var pad = new string('\t', indent);
        var name = $"__q_{qCounter++}";
        sb.Append($"{name} := ");
        EmitExpression(sb, pe.Operand);
        sb.AppendLine();
        sb.Append(pad);
        sb.AppendLine($"if !{name}.IsOk {{");
        sb.Append(pad);
        sb.AppendLine($"\treturn overt.Err[overt.Unit, overt.IoError]({name}.Err)");
        sb.Append(pad);
        sb.Append("}");
    }

    private static void EmitExpression(StringBuilder sb, Expression expr)
    {
        switch (expr)
        {
            case StringLiteralExpr sl:
                // sl.Value is the raw lexeme including surrounding quotes
                // and the original source's escape sequences. Overt's
                // string escape syntax is C-compatible (\n, \t, \\, \"),
                // so the lexeme transfers to Go verbatim for the scaffold-
                // grade subset we currently support. A future feature
                // expansion that allows `\u` sequences will need a real
                // decode/re-encode pass; cf. the C# emitter at
                // CSharpEmitter.cs around line 2205.
                sb.Append(sl.Value);
                break;

            case IntegerLiteralExpr il:
                // Lexeme: decimal / hex (0x...) / binary (0b...) — Go
                // accepts the same set verbatim.
                sb.Append(il.Lexeme);
                break;

            case BooleanLiteralExpr bl:
                sb.Append(bl.Value ? "true" : "false");
                break;

            case UnitExpr:
                sb.Append("overt.UnitValue");
                break;

            case BinaryExpr be:
                sb.Append('(');
                EmitExpression(sb, be.Left);
                sb.Append(' ');
                sb.Append(BinaryOpToGo(be.Op));
                sb.Append(' ');
                EmitExpression(sb, be.Right);
                sb.Append(')');
                break;

            case UnaryExpr ue:
                sb.Append('(');
                sb.Append(UnaryOpToGo(ue.Op));
                EmitExpression(sb, ue.Operand);
                sb.Append(')');
                break;

            case CallExpr call:
                EmitCall(sb, call);
                break;

            case RecordLiteralExpr rl:
                // Overt: `Name { field = value, ... }`
                // Go:    `Name{field: value, ...}`
                // The TypeTarget is parsed as either an IdentifierExpr
                // (single-segment record name) or a FieldAccess chain
                // (Mod.Type). For the scaffold we only handle the
                // single-segment form.
                if (rl.TypeTarget is IdentifierExpr typeId)
                {
                    sb.Append(typeId.Name);
                }
                else
                {
                    throw new NotSupportedException(
                        "Go back end does not yet handle dotted record-type targets; "
                        + $"got {rl.TypeTarget.GetType().Name}.");
                }
                sb.Append('{');
                for (var i = 0; i < rl.Fields.Length; i++)
                {
                    if (i > 0) sb.Append(", ");
                    sb.Append(rl.Fields[i].Name);
                    sb.Append(": ");
                    EmitExpression(sb, rl.Fields[i].Value);
                }
                sb.Append('}');
                break;

            case FieldAccessExpr fa:
                // Plain Go field access. The type checker already
                // resolved that the LHS has a field by this name,
                // and Go accepts the same dot syntax.
                EmitExpression(sb, fa.Target);
                sb.Append('.');
                sb.Append(fa.FieldName);
                break;

            case IdentifierExpr id:
                // Heuristic: lowercase-leading names are local fns or
                // prelude exports (println / eprintln); uppercase-leading
                // are constructors (Ok / Err) routed through the runtime.
                sb.Append(MapIdentifier(id.Name));
                break;

            default:
                throw new NotSupportedException(
                    $"Go back end does not yet handle expression {expr.GetType().Name}.");
        }
    }

    private static string BinaryOpToGo(BinaryOp op) => op switch
    {
        BinaryOp.Add => "+",
        BinaryOp.Subtract => "-",
        BinaryOp.Multiply => "*",
        BinaryOp.Divide => "/",
        BinaryOp.Modulo => "%",
        BinaryOp.Equal => "==",
        BinaryOp.NotEqual => "!=",
        BinaryOp.Less => "<",
        BinaryOp.LessEqual => "<=",
        BinaryOp.Greater => ">",
        BinaryOp.GreaterEqual => ">=",
        BinaryOp.LogicalAnd => "&&",
        BinaryOp.LogicalOr => "||",
        _ => throw new NotSupportedException(
            "Go back end does not yet handle binary operator " + op
            + " (pipe operators desugar in a separate pass that's not wired here)."),
    };

    private static string UnaryOpToGo(UnaryOp op) => op switch
    {
        UnaryOp.Negate => "-",
        UnaryOp.LogicalNot => "!",
        _ => throw new NotSupportedException(
            "Go back end does not yet handle unary operator " + op),
    };

    private static void EmitCall(StringBuilder sb, CallExpr call)
    {
        // Special-case the constructors: `Ok(x)` and `Err(e)` need
        // explicit type parameters in Go, since there's no contextual
        // type inference at the call site.
        if (call.Callee is IdentifierExpr { Name: "Ok" } && call.Arguments.Length == 1)
        {
            sb.Append("overt.Ok[overt.Unit, overt.IoError](");
            EmitExpression(sb, call.Arguments[0].Value);
            sb.Append(')');
            return;
        }
        if (call.Callee is IdentifierExpr { Name: "Err" } && call.Arguments.Length == 1)
        {
            sb.Append("overt.Err[overt.Unit, overt.IoError](");
            EmitExpression(sb, call.Arguments[0].Value);
            sb.Append(')');
            return;
        }

        EmitExpression(sb, call.Callee);
        sb.Append('(');
        for (var i = 0; i < call.Arguments.Length; i++)
        {
            if (i > 0) sb.Append(", ");
            EmitExpression(sb, call.Arguments[i].Value);
        }
        sb.Append(')');
    }

    private static string MapIdentifier(string name) => name switch
    {
        "println" => "overt.Println",
        "eprintln" => "overt.Eprintln",
        _ => name,
    };

}
