using System.Collections.Immutable;
using System.Text;
using Overt.Compiler.Syntax;

namespace Overt.Backend.CSharp;

/// <summary>
/// First-pass C# transpiler. Walks the Overt AST and emits C# source text. Deliberately
/// untyped: no symbol resolution, no effect inference, no type checking. Constructs
/// that need semantic information to emit correctly produce placeholder code with a
/// <c>// TODO:</c> comment. The goal of this pass is end-to-end plumbing, not a
/// production backend.
///
/// Rough mapping:
/// <list type="bullet">
///   <item>Module → <c>namespace Overt.Generated.&lt;Name&gt;; public static class Module</c></item>
///   <item>fn → <c>public static</c> method on the module class</item>
///   <item>record → C# <c>sealed record</c></item>
///   <item>enum → abstract base record + one sealed record per variant</item>
///   <item>type alias → <c>using Name = Target;</c> (no refinement enforcement yet)</item>
///   <item>extern → method stub with a <c>// extern</c> comment</item>
///   <item>if/match/with/interp → C# expression forms (<c>?:</c>, <c>switch</c>, <c>with</c>, <c>$"..."</c>)</item>
///   <item>pipe (<c>|&gt;</c>) → call-arg splice at emit time</item>
///   <item>? propagation → <c>.Unwrap()</c> (runtime shim; full lowering comes with the type checker)</item>
///   <item>parallel/race/trace/unsafe → placeholder wrappers</item>
///   <item>effect rows → discarded</item>
/// </list>
/// </summary>
public sealed class CSharpEmitter
{
    private readonly IndentedWriter _w;

    private CSharpEmitter(IndentedWriter w) { _w = w; }

    public static string Emit(ModuleDecl module)
    {
        var sb = new StringBuilder();
        var emitter = new CSharpEmitter(new IndentedWriter(sb));
        emitter.EmitModule(module);
        return sb.ToString();
    }

    // ------------------------------------------------------------- module

    private void EmitModule(ModuleDecl module)
    {
        _w.WriteLine("// <auto-generated>");
        _w.WriteLine($"// Transpiled from Overt module `{module.Name}`.");
        _w.WriteLine("// </auto-generated>");
        _w.WriteLine("#nullable enable");
        _w.WriteLine();
        _w.WriteLine("using System;");
        _w.WriteLine("using System.Threading.Tasks;");
        _w.WriteLine("using Overt.Runtime;");
        _w.WriteLine("using static Overt.Runtime.Prelude;");
        _w.WriteLine();
        _w.WriteLine($"namespace Overt.Generated.{PascalCase(module.Name)};");
        _w.WriteLine();

        // Type aliases emit as file-scoped using-directives at the top. C# requires them
        // before any type declarations.
        foreach (var decl in module.Declarations.OfType<TypeAliasDecl>())
        {
            EmitTypeAlias(decl);
        }
        if (module.Declarations.OfType<TypeAliasDecl>().Any())
        {
            _w.WriteLine();
        }

        foreach (var decl in module.Declarations.Where(d => d is not TypeAliasDecl))
        {
            EmitDeclaration(decl);
            _w.WriteLine();
        }

        // Functions and externs go on a single static `Module` class. For clarity we
        // emit that class once, wrapping all functions and externs collected.
        var fnLike = module.Declarations
            .Where(d => d is FunctionDecl or ExternDecl)
            .ToImmutableArray();
        if (fnLike.Length > 0)
        {
            _w.WriteLine("public static class Module");
            _w.WriteLine("{");
            using (_w.Indent())
            {
                foreach (var decl in fnLike)
                {
                    switch (decl)
                    {
                        case FunctionDecl f: EmitFunction(f); break;
                        case ExternDecl x: EmitExtern(x); break;
                    }
                    _w.WriteLine();
                }
            }
            _w.WriteLine("}");
        }
    }

    // ------------------------------------------------------ declarations

    private void EmitDeclaration(Declaration decl)
    {
        switch (decl)
        {
            case RecordDecl r: EmitRecord(r); break;
            case EnumDecl e: EmitEnum(e); break;
            case FunctionDecl:
            case ExternDecl:
                // Emitted inside the Module class by EmitModule.
                break;
        }
    }

    private void EmitRecord(RecordDecl rec)
    {
        EmitAnnotationComments(rec.Annotations);
        _w.Write("public sealed record ");
        _w.Write(rec.Name);
        _w.Write("(");
        for (var i = 0; i < rec.Fields.Length; i++)
        {
            if (i > 0) _w.Write(", ");
            EmitType(rec.Fields[i].Type);
            _w.Write(" ");
            _w.Write(EscapeId(rec.Fields[i].Name));
        }
        _w.WriteLine(");");
    }

    private void EmitEnum(EnumDecl e)
    {
        EmitAnnotationComments(e.Annotations);
        _w.Write($"public abstract record {e.Name}");
        _w.WriteLine(";");
        foreach (var variant in e.Variants)
        {
            _w.Write("public sealed record ");
            _w.Write($"{e.Name}_{variant.Name}");
            if (variant.Fields.Length > 0)
            {
                _w.Write("(");
                for (var i = 0; i < variant.Fields.Length; i++)
                {
                    if (i > 0) _w.Write(", ");
                    EmitType(variant.Fields[i].Type);
                    _w.Write(" ");
                    _w.Write(EscapeId(variant.Fields[i].Name));
                }
                _w.Write(")");
            }
            _w.Write($" : {e.Name}");
            _w.WriteLine(";");
        }
    }

    private void EmitTypeAlias(TypeAliasDecl t)
    {
        // C# only supports using-aliases for types that can be spelled out. Generic
        // parameters on the alias and `where` predicates are dropped with a comment.
        if (t.TypeParameters.Length > 0 || t.Predicate is not null)
        {
            _w.Write($"// TODO: type alias `{t.Name}` with ");
            if (t.TypeParameters.Length > 0) _w.Write("generic params ");
            if (t.Predicate is not null) _w.Write("refinement predicate ");
            _w.WriteLine("- emitted as direct alias, constraints dropped");
        }
        _w.Write($"using {t.Name} = ");
        EmitType(t.Target);
        _w.WriteLine(";");
    }

    private void EmitFunction(FunctionDecl fn)
    {
        EmitEffectRowComment(fn.Effects);
        _w.Write("public static ");
        if (fn.ReturnType is { } rt)
        {
            EmitType(rt);
        }
        else
        {
            _w.Write("Unit");
        }
        _w.Write($" {EscapeId(fn.Name)}");
        if (fn.TypeParameters.Length > 0)
        {
            _w.Write("<");
            _w.Write(string.Join(", ", fn.TypeParameters));
            _w.Write(">");
        }
        _w.Write("(");
        for (var i = 0; i < fn.Parameters.Length; i++)
        {
            if (i > 0) _w.Write(", ");
            EmitType(fn.Parameters[i].Type);
            _w.Write(" ");
            _w.Write(EscapeId(fn.Parameters[i].Name));
        }
        _w.WriteLine(")");
        EmitBlockAsMethodBody(fn.Body, fn.ReturnType);
    }

    private void EmitExtern(ExternDecl x)
    {
        var unsafePrefix = x.IsUnsafe ? "// unsafe " : "// ";
        _w.WriteLine($"{unsafePrefix}extern \"{x.Platform}\" binds \"{x.BindsTarget}\""
            + (x.FromLibrary is { } lib ? $" from \"{lib}\"" : ""));
        EmitEffectRowComment(x.Effects);
        _w.Write("public static ");
        if (x.ReturnType is { } rt)
        {
            EmitType(rt);
        }
        else
        {
            _w.Write("Unit");
        }
        _w.Write($" {EscapeId(x.Name)}(");
        for (var i = 0; i < x.Parameters.Length; i++)
        {
            if (i > 0) _w.Write(", ");
            EmitType(x.Parameters[i].Type);
            _w.Write(" ");
            _w.Write(EscapeId(x.Parameters[i].Name));
        }
        _w.WriteLine(")");
        _w.WriteLine("{");
        using (_w.Indent())
        {
            _w.WriteLine("throw new NotImplementedException(\"extern binding not yet wired up\");");
        }
        _w.WriteLine("}");
    }

    // ----------------------------------------------------- type expressions

    private void EmitType(TypeExpr type)
    {
        switch (type)
        {
            case NamedType nt:
                _w.Write(MapTypeName(nt.Name));
                if (nt.TypeArguments.Length > 0)
                {
                    _w.Write("<");
                    for (var i = 0; i < nt.TypeArguments.Length; i++)
                    {
                        if (i > 0) _w.Write(", ");
                        EmitType(nt.TypeArguments[i]);
                    }
                    _w.Write(">");
                }
                break;

            case UnitType:
                _w.Write("Unit");
                break;

            case FunctionType ft:
                // Map to Func<,> (or Action<> for Unit return). Effect row is discarded.
                if (IsUnit(ft.ReturnType))
                {
                    if (ft.Parameters.Length == 0) _w.Write("Action");
                    else
                    {
                        _w.Write("Action<");
                        for (var i = 0; i < ft.Parameters.Length; i++)
                        {
                            if (i > 0) _w.Write(", ");
                            EmitType(ft.Parameters[i]);
                        }
                        _w.Write(">");
                    }
                }
                else
                {
                    _w.Write("Func<");
                    foreach (var p in ft.Parameters)
                    {
                        EmitType(p);
                        _w.Write(", ");
                    }
                    EmitType(ft.ReturnType);
                    _w.Write(">");
                }
                break;
        }
    }

    private static bool IsUnit(TypeExpr t) => t is UnitType;

    private static string MapTypeName(string name) => name switch
    {
        "Int" => "int",
        "Float" => "double",
        "Bool" => "bool",
        "String" => "string",
        _ => name,
    };

    // ---------------------------------------------------- blocks + stmts

    private void EmitBlockAsMethodBody(BlockExpr block, TypeExpr? returnType)
    {
        _w.WriteLine("{");
        using (_w.Indent())
        {
            foreach (var stmt in block.Statements)
            {
                EmitStatement(stmt);
            }
            if (block.TrailingExpression is { } tail)
            {
                _w.Write("return ");
                EmitExpression(tail);
                _w.WriteLine(";");
            }
            else if (returnType is UnitType)
            {
                _w.WriteLine("return Unit.Value;");
            }
        }
        _w.WriteLine("}");
    }

    private void EmitStatement(Statement stmt)
    {
        switch (stmt)
        {
            case LetStmt ls:
                _w.Write("var ");
                EmitPatternForBinding(ls.Target);
                _w.Write(" = ");
                EmitExpression(ls.Initializer);
                _w.WriteLine(";");
                break;

            case AssignmentStmt asn:
                _w.Write(EscapeId(asn.Name));
                _w.Write(" = ");
                EmitExpression(asn.Value);
                _w.WriteLine(";");
                break;

            case ExpressionStmt es:
                EmitExpressionAsStatement(es.Expression);
                break;
        }
    }

    /// <summary>
    /// Emit an expression as a C# statement. Control-flow constructs that look natural
    /// as expressions in Overt (<c>if</c>, <c>while</c>, <c>match</c>, <c>unsafe</c>,
    /// <c>trace</c>, and blocks) map directly to C#'s statement-level forms when the
    /// value is discarded. Everything else emits as <c>expr;</c>.
    /// </summary>
    private void EmitExpressionAsStatement(Expression expr)
    {
        switch (expr)
        {
            case IfExpr ie:
                _w.Write("if (");
                EmitExpression(ie.Condition);
                _w.WriteLine(")");
                EmitBlockAsStatement(ie.Then);
                if (ie.Else is { } elseBlock)
                {
                    _w.WriteLine("else");
                    EmitBlockAsStatement(elseBlock);
                }
                break;

            case WhileExpr we:
                _w.Write("while (");
                EmitExpression(we.Condition);
                _w.WriteLine(")");
                EmitBlockAsStatement(we.Body);
                break;

            case BlockExpr b:
                EmitBlockAsStatement(b);
                break;

            case UnsafeExpr ux:
                EmitBlockAsStatement(ux.Body);
                break;

            case TraceExpr tx:
                EmitBlockAsStatement(tx.Body);
                break;

            // Everything else: just write the expression plus a trailing `;`. C# will
            // reject anything that isn't a valid statement-expression (calls, assignments,
            // increments, etc.) — that's the type checker's job later.
            default:
                EmitExpression(expr);
                _w.WriteLine(";");
                break;
        }
    }

    /// <summary>
    /// Emits a pattern as the left-hand side of a <c>var</c> binding. Tuple patterns
    /// become C# tuple-var syntax; identifier patterns are just the name.
    /// </summary>
    private void EmitPatternForBinding(Pattern pattern)
    {
        switch (pattern)
        {
            case IdentifierPattern ip:
                _w.Write(EscapeId(ip.Name));
                break;
            case TuplePattern tp:
                _w.Write("(");
                for (var i = 0; i < tp.Elements.Length; i++)
                {
                    if (i > 0) _w.Write(", ");
                    EmitPatternForBinding(tp.Elements[i]);
                }
                _w.Write(")");
                break;
            case WildcardPattern:
                _w.Write("_");
                break;
            default:
                _w.Write("/* TODO pattern */ _");
                break;
        }
    }

    // -------------------------------------------------------- expressions

    private void EmitExpression(Expression expr)
    {
        switch (expr)
        {
            case IntegerLiteralExpr i:
                _w.Write(i.Lexeme.Replace("_", ""));
                break;

            case FloatLiteralExpr f:
                _w.Write(f.Lexeme.Replace("_", ""));
                break;

            case BooleanLiteralExpr b:
                _w.Write(b.Value ? "true" : "false");
                break;

            case StringLiteralExpr s:
                _w.Write(s.Value); // already includes surrounding quotes
                break;

            case UnitExpr:
                _w.Write("Unit.Value");
                break;

            case IdentifierExpr id:
                _w.Write(EscapeId(id.Name));
                break;

            case FieldAccessExpr fa:
                // Without type info, we can't tell an enum variant reference
                // (<c>ConnectionState.Closed</c>) from an ordinary field access
                // (<c>user.name</c>). Apply a heuristic: when the target is a bare
                // identifier whose name is PascalCase and the accessed name is also
                // PascalCase, treat it as an enum-variant reference and emit the
                // flat <c>Name_Variant</c> form used by the enum lowering, as a
                // constructor call with no args. Everything else is a member access.
                if (IsLikelyEnumVariantRef(fa))
                {
                    // Widening cast to the enum base type: target-typing `Ok(variant)`
                    // needs T to unify with the base, not the specific variant's type.
                    var baseName = ((IdentifierExpr)fa.Target).Name;
                    _w.Write($"(({baseName})new {baseName}_{fa.FieldName}())");
                }
                else
                {
                    EmitExpression(fa.Target);
                    _w.Write(".");
                    _w.Write(EscapeId(fa.FieldName));
                }
                break;

            case CallExpr c:
                EmitCall(c);
                break;

            case PropagateExpr pr:
                _w.Write("(");
                EmitExpression(pr.Operand);
                _w.Write(").Unwrap()");
                break;

            case BinaryExpr be:
                EmitBinary(be);
                break;

            case UnaryExpr ue:
                _w.Write(ue.Op == UnaryOp.Negate ? "-(" : "!(");
                EmitExpression(ue.Operand);
                _w.Write(")");
                break;

            case InterpolatedStringExpr isx:
                EmitInterpolatedString(isx);
                break;

            case IfExpr ie:
                EmitIf(ie);
                break;

            case WhileExpr we:
                _w.Write("((Func<Unit>)(() => { while (");
                EmitExpression(we.Condition);
                _w.Write(") ");
                EmitBlockAsStatement(we.Body);
                _w.Write(" return Unit.Value; }))()");
                break;

            case BlockExpr b:
                EmitBlockAsExpression(b);
                break;

            case TupleExpr te:
                _w.Write("(");
                for (var i = 0; i < te.Elements.Length; i++)
                {
                    if (i > 0) _w.Write(", ");
                    EmitExpression(te.Elements[i]);
                }
                _w.Write(")");
                break;

            case RecordLiteralExpr rl:
                EmitRecordLiteral(rl);
                break;

            case WithExpr w:
                _w.Write("(");
                EmitExpression(w.Target);
                _w.Write(" with { ");
                for (var i = 0; i < w.Updates.Length; i++)
                {
                    if (i > 0) _w.Write(", ");
                    _w.Write(EscapeId(w.Updates[i].Name));
                    _w.Write(" = ");
                    EmitExpression(w.Updates[i].Value);
                }
                _w.Write(" })");
                break;

            case MatchExpr me:
                EmitMatch(me);
                break;

            case ParallelExpr:
                _w.Write("/* TODO: parallel {...} - requires async runtime */ default!");
                break;

            case RaceExpr:
                _w.Write("/* TODO: race {...} - requires async runtime */ default!");
                break;

            case UnsafeExpr ux:
                // unsafe-block semantics don't exist in C# the same way. Just emit the body.
                EmitBlockAsExpression(ux.Body);
                break;

            case TraceExpr tx:
                // trace is pass-through at the value level for the untyped pass.
                EmitBlockAsExpression(tx.Body);
                break;

            default:
                _w.Write($"/* TODO: {expr.GetType().Name} */ default!");
                break;
        }
    }

    private void EmitCall(CallExpr c)
    {
        EmitExpression(c.Callee);
        _w.Write("(");
        for (var i = 0; i < c.Arguments.Length; i++)
        {
            if (i > 0) _w.Write(", ");
            // Named-argument calls pass through to C# named-argument syntax.
            if (c.Arguments[i].Name is { } name)
            {
                _w.Write(EscapeId(name));
                _w.Write(": ");
            }
            EmitExpression(c.Arguments[i].Value);
        }
        _w.Write(")");
    }

    private void EmitBinary(BinaryExpr be)
    {
        // Pipes rewrite to call-arg splicing: `x |> f(a, b)` → `f(x, a, b)`.
        if (be.Op is BinaryOp.PipeCompose or BinaryOp.PipePropagate)
        {
            EmitPipe(be);
            return;
        }

        _w.Write("(");
        EmitExpression(be.Left);
        _w.Write(" ");
        _w.Write(BinaryOpToCSharp(be.Op));
        _w.Write(" ");
        EmitExpression(be.Right);
        _w.Write(")");
    }

    private void EmitPipe(BinaryExpr be)
    {
        // Build the "call with x spliced as first arg" form. If the RHS is a call,
        // splice; otherwise treat RHS as unary.
        if (be.Right is CallExpr call)
        {
            _w.Write("(");
            EmitExpression(call.Callee);
            _w.Write("(");
            EmitExpression(be.Left);
            foreach (var arg in call.Arguments)
            {
                _w.Write(", ");
                if (arg.Name is { } name)
                {
                    _w.Write(name);
                    _w.Write(": ");
                }
                EmitExpression(arg.Value);
            }
            _w.Write("))");
        }
        else
        {
            _w.Write("(");
            EmitExpression(be.Right);
            _w.Write("(");
            EmitExpression(be.Left);
            _w.Write("))");
        }
        if (be.Op == BinaryOp.PipePropagate)
        {
            _w.Write(".Unwrap()");
        }
    }

    private static string BinaryOpToCSharp(BinaryOp op) => op switch
    {
        BinaryOp.Add => "+",
        BinaryOp.Subtract => "-",
        BinaryOp.Multiply => "*",
        BinaryOp.Divide => "/",
        BinaryOp.Modulo => "%",
        BinaryOp.Equal => "==",
        BinaryOp.NotEqual => "!=",
        BinaryOp.Less => "<",
        BinaryOp.LessEqual => "<=",
        BinaryOp.Greater => ">",
        BinaryOp.GreaterEqual => ">=",
        BinaryOp.LogicalAnd => "&&",
        BinaryOp.LogicalOr => "||",
        _ => "?",
    };

    private void EmitInterpolatedString(InterpolatedStringExpr isx)
    {
        // C# interpolated string: $"...{expr}..."
        _w.Write("$\"");
        for (var i = 0; i < isx.Parts.Length; i++)
        {
            var part = isx.Parts[i];
            switch (part)
            {
                case StringLiteralPart lp:
                    _w.Write(StripQuotesForInterp(lp.Text, isFirst: i == 0, isLast: i == isx.Parts.Length - 1));
                    break;
                case StringInterpolationPart ip:
                    _w.Write("{");
                    EmitExpression(ip.Expression);
                    _w.Write("}");
                    break;
            }
        }
        _w.Write("\"");
    }

    // Head/tail literal parts carry their surrounding quote(s) from the lexer's segmenting;
    // the middle parts don't. Strip them when emitting so the whole thing reads as a single
    // C# interpolated string.
    private static string StripQuotesForInterp(string raw, bool isFirst, bool isLast)
    {
        var s = raw;
        if (isFirst && s.StartsWith('"')) s = s[1..];
        if (isLast && s.EndsWith('"')) s = s[..^1];
        return s;
    }

    private void EmitIf(IfExpr ie)
    {
        // C# has a ternary operator; we lower Overt's if-expression to a ternary when
        // both arms are expressions. If the else is absent, the else-value is Unit.Value.
        _w.Write("((");
        EmitExpression(ie.Condition);
        _w.Write(") ? ");
        EmitBlockAsExpression(ie.Then);
        _w.Write(" : ");
        if (ie.Else is { } elseBlock)
        {
            EmitBlockAsExpression(elseBlock);
        }
        else
        {
            _w.Write("Unit.Value");
        }
        _w.Write(")");
    }

    private void EmitMatch(MatchExpr me)
    {
        _w.Write("(");
        EmitExpression(me.Scrutinee);
        _w.WriteLine(" switch");
        _w.WriteLine("{");
        using (_w.Indent())
        {
            foreach (var arm in me.Arms)
            {
                EmitPatternForMatch(arm.Pattern);
                _w.Write(" => ");
                EmitExpression(arm.Body);
                _w.WriteLine(",");
            }
        }
        _w.Write("})");
    }

    private void EmitPatternForMatch(Pattern p)
    {
        switch (p)
        {
            case WildcardPattern: _w.Write("_"); break;
            case IdentifierPattern id: _w.Write($"var {EscapeId(id.Name)}"); break;
            case PathPattern pp:
                // `A.B` with no args — emit the sealed-record type name (A_B) for
                // pattern-matching against the variant.
                _w.Write(JoinPath(pp.Path));
                _w.Write(" _");
                break;
            case ConstructorPattern cp:
                // `Ok(x)` or `A.B(x, y)` — emit as a positional record pattern. Unqualified
                // variant names (single-segment path) are left to resolve via type context
                // (e.g. `Ok` / `Err` / `Some` / `None` from the runtime prelude).
                _w.Write(JoinPath(cp.Path));
                if (cp.Arguments.Length > 0)
                {
                    _w.Write("(");
                    for (var i = 0; i < cp.Arguments.Length; i++)
                    {
                        if (i > 0) _w.Write(", ");
                        EmitPatternForMatch(cp.Arguments[i]);
                    }
                    _w.Write(")");
                }
                break;
            case RecordPattern rp:
                _w.Write(JoinPath(rp.Path));
                _w.Write(" { ");
                for (var i = 0; i < rp.Fields.Length; i++)
                {
                    if (i > 0) _w.Write(", ");
                    _w.Write(EscapeId(rp.Fields[i].Name));
                    _w.Write(": ");
                    EmitPatternForMatch(rp.Fields[i].Subpattern);
                }
                _w.Write(" }");
                break;
            case TuplePattern tp:
                _w.Write("(");
                for (var i = 0; i < tp.Elements.Length; i++)
                {
                    if (i > 0) _w.Write(", ");
                    EmitPatternForMatch(tp.Elements[i]);
                }
                _w.Write(")");
                break;
        }
    }

    /// <summary>
    /// Join a dotted path for an enum variant reference. Multi-segment paths collapse
    /// to <c>First_Second</c> (the emitted sealed-record name); single-segment paths
    /// pass through so unqualified variants like <c>Ok</c> / <c>Some</c> resolve against
    /// whatever type context (Result / Option) is in scope.
    /// </summary>
    private static string JoinPath(System.Collections.Immutable.ImmutableArray<string> path)
        => path.Length == 1 ? path[0] : string.Join("_", path);

    private void EmitBlockAsStatement(BlockExpr block)
    {
        _w.WriteLine("{");
        using (_w.Indent())
        {
            foreach (var stmt in block.Statements) EmitStatement(stmt);
            if (block.TrailingExpression is { } tail)
            {
                EmitExpression(tail);
                _w.WriteLine(";");
            }
        }
        _w.WriteLine("}");
    }

    /// <summary>
    /// Emit a block as an expression. Pure trailing-expression blocks inline directly.
    /// Blocks with statements become immediately-invoked lambdas so the full body runs.
    /// </summary>
    private void EmitBlockAsExpression(BlockExpr block)
    {
        if (block.Statements.Length == 0 && block.TrailingExpression is { } only)
        {
            EmitExpression(only);
            return;
        }

        _w.Write("((Func<object?>)(() => { ");
        foreach (var stmt in block.Statements)
        {
            EmitStatement(stmt);
        }
        if (block.TrailingExpression is { } tail)
        {
            _w.Write("return ");
            EmitExpression(tail);
            _w.Write(";");
        }
        else
        {
            _w.Write("return Unit.Value;");
        }
        _w.Write(" }))()");
    }

    private void EmitRecordLiteral(RecordLiteralExpr rl)
    {
        // A dotted-path record literal (e.g. `Tree.Node { ... }`) refers to an enum
        // variant, emitted as a flat sealed-record type named `Enum_Variant`. We cast
        // to the enum base type so `Ok(variant)` / `Err(variant)` target-type correctly
        // at the call site — C# will otherwise infer the most-specific type and fail to
        // find an implicit conversion for the marker.
        if (rl.TypeTarget is FieldAccessExpr fa
            && fa.Target is IdentifierExpr enumName
            && IsPascalCase(enumName.Name)
            && IsPascalCase(fa.FieldName))
        {
            _w.Write($"(({enumName.Name})new {enumName.Name}_{fa.FieldName}(");
            EmitFieldInits(rl.Fields);
            _w.Write("))");
            return;
        }

        _w.Write("new ");
        EmitExpression(rl.TypeTarget);
        _w.Write("(");
        EmitFieldInits(rl.Fields);
        _w.Write(")");
    }

    private void EmitFieldInits(ImmutableArray<FieldInit> fields)
    {
        for (var i = 0; i < fields.Length; i++)
        {
            if (i > 0) _w.Write(", ");
            _w.Write(EscapeId(fields[i].Name));
            _w.Write(": ");
            EmitExpression(fields[i].Value);
        }
    }

    // ------------------------------------------------------------ helpers

    private void EmitAnnotationComments(ImmutableArray<Annotation> annotations)
    {
        foreach (var a in annotations)
        {
            var args = a.Arguments.Length > 0 ? $"({string.Join(", ", a.Arguments)})" : "";
            _w.WriteLine($"// @{a.Name}{args}");
        }
    }

    private void EmitEffectRowComment(EffectRow? row)
    {
        if (row is null || row.Effects.Length == 0) return;
        _w.WriteLine($"// !{{{string.Join(", ", row.Effects)}}}");
    }

    private static string PascalCase(string snake)
    {
        if (string.IsNullOrEmpty(snake)) return snake;
        var parts = snake.Split('_');
        return string.Concat(parts.Select(p =>
            p.Length == 0 ? p : char.ToUpperInvariant(p[0]) + p[1..]));
    }

    private static bool IsLikelyEnumVariantRef(FieldAccessExpr fa)
        => fa.Target is IdentifierExpr id
           && IsPascalCase(id.Name)
           && IsPascalCase(fa.FieldName);

    private static bool IsPascalCase(string s)
        => s.Length > 0 && char.IsUpper(s[0]) && !s.Contains('_');

    /// <summary>
    /// C# reserved and contextual keywords. Overt identifiers that happen to spell these
    /// must be prefixed with <c>@</c> in emitted code (e.g. <c>event</c> → <c>@event</c>).
    /// </summary>
    private static readonly HashSet<string> CSharpKeywords = new(StringComparer.Ordinal)
    {
        "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char",
        "checked", "class", "const", "continue", "decimal", "default", "delegate",
        "do", "double", "else", "enum", "event", "explicit", "extern", "false",
        "finally", "fixed", "float", "for", "foreach", "goto", "if", "implicit",
        "in", "int", "interface", "internal", "is", "lock", "long", "namespace",
        "new", "null", "object", "operator", "out", "override", "params", "private",
        "protected", "public", "readonly", "ref", "return", "sbyte", "sealed",
        "short", "sizeof", "stackalloc", "static", "string", "struct", "switch",
        "this", "throw", "true", "try", "typeof", "uint", "ulong", "unchecked",
        "unsafe", "ushort", "using", "virtual", "void", "volatile", "while",
    };

    /// <summary>
    /// Escape an Overt identifier for use in emitted C#. Adds the <c>@</c> prefix when
    /// the name would otherwise collide with a C# keyword. Called on every identifier
    /// slot that the emitter writes — declarations, references, parameters, fields.
    /// Variant paths like <c>Tree.Node</c> stay raw because they match the emitted
    /// variant record names directly.
    /// </summary>
    private static string EscapeId(string name) =>
        CSharpKeywords.Contains(name) ? "@" + name : name;
}
